### ISSUE TITLE
in lx_nand_flash_data_page_copy.c judge NOT SEQUENTIAL

### ISSUE THREAD

**Issue by EricXue2013** [eclipse-threadx/levelx#18]
levelx  6.2.1
in  file    lx_nand_flash_data_page_copy.c

/* Check if the pages in destination block is still sequential.  */
 if ((destination_page) != (logical_sector + i % nand_flash -> lx_nand_flash_pages_per_block))
{
        /* Mark the block status as non sequential.  */
        dest_block_status |= LX_NAND_BLOCK_STATUS_NON_SEQUENTIAL;
}

should be 
/* Check if the pages in destination block is still sequential.  */
 if ( destination_page != ((logical_sector + i )% nand_flash -> lx_nand_flash_pages_per_block))
{
        /* Mark the block status as non sequential.  */
        dest_block_status |= LX_NAND_BLOCK_STATUS_NON_SEQUENTIAL;
}

**Comment by xiuwencai** [comment]
Thank you for reporting the bug. We will fix it.
